name: Checkstyle

on:
  pull_request:
    branches:
      - master

jobs:
  style:
    name: Checkstyle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkstyle
        uses: dbelyaev/action-checkstyle@v1.16.5
        with:
          level: warning
          fail_on_error: true