name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master


jobs:
  build: # Attempt to build the project
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

    test: # Run all JUnit tests
      name: Test
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            distribution: 'corretto'
            java-version: '21'

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew

        - name: Run tests
          run: ./gradlew test