name: CI

on:
  push:
    branches:
      - master
      - develop # Temporary
  pull_request:
    branches:
      - master


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

  style:
    name: Checkstyle
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkstyle
        uses: dbelyaev/action-checkstyle@v1.16.5
        with:
          level: warning
          fail_on_error: true